apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-app-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs-fspool-cluster  
  volumeMode: Filesystem
