kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: TWlCbzIwMA==
  password: Z2hwXzl3VEYwOGxhekZNdUxFakJ5TmZZazdGTldPWjVSYTJYQ2FjVA==
type: kubernetes.io/basic-auth
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: MjMzOHQ3ZWNnbnU1NGJjcmU=
type: Opaque